### ISSUE TITLE
Black screen in Firefox - WebGL Failure

### ISSUE THREAD

**Issue by mon** [kepstin/0x40hues-html5#2] opened 2015-06-02 05:56 UTC
As title, console log:

```
"Loading respack at respacks/builtin" hues.js:66:24
"Loading respack at respacks/0x40%20Hues%205.0%20Defaults" hues.js:66:24
"Loaded respack info for builtin" hues.js:66:180
"Loaded respack info for 0x40 Hues v5.0 Defaults" hues.js:66:180
"Loaded 64 hues from builtin" hues.js:66:385
"Respack has no images: builtin" hues.js:68:244
"Respack contains no songs: builtin" hues.js:67:238
"All content from respack builtin has loaded" hues.js:69:127
"Respack contains no hues: 0x40 Hues v5.0 Defaults" hues.js:66:469
"Loaded 21 songs from 0x40 Hues v5.0 Defaults" hues.js:67:152
"If you got a 404 error there it was expected and unavoidable... You can just ignore it." hues.js:50:78
"Loaded 130 images from 0x40 Hues v5.0 Defaults" hues.js:68:156
"All content from respack 0x40 Hues v5.0 Defaults has loaded" hues.js:69:127
"Loaded hues:" hues.js:72:0
Array [ Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, 54 more… ] hues.js:72:28
"Loaded songs:" hues.js:73:0
Array [ Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, 11 more… ] hues.js:73:29
"Loaded images:" hues.js:74:0
Array [ Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, 120 more… ] hues.js:74:30
"Shader link failure:" hues-effect.js:28:180
"Failed to create D3D shaders.
" hues-effect.js:28:216
"Could not link shader program" hues-ui.js:27:396
Error: WebGL: linkProgram: Failed to link, leaving the following log:
Failed to create D3D shaders.

 hues-effect.js:28:106
```

**Comment by kepstin** [comment] 2015-06-02 11:56
Interesting, all of the computers I've tried it on were using native OpenGL, rather than attempting to convert the GL shaders to D3D. That log really sucks, it doesn't say _why_ the shader failed to compile. (In GL, it will give actual errors with line numbers and stuff)

What graphics card and driver version are you using?

**Comment by kepstin** [comment] 2015-06-02 12:06
Also, can you say which exact Firefox version you're using? The "ANGLE" engine they use to do the shader translation varies quite a bit between versions.

**Comment by mon** [comment] 2015-06-02 12:37
Firefox 38.0.1, Windows 8.1, Radeon HD 7770, Catalyst 14.9

**Comment by kepstin** [comment] 2015-06-02 12:38
Alright, I have a computer around with similar specs. I'll see if I can reproduce it here, thanks.

**Comment by kepstin** [comment] 2015-06-02 13:25
I tested this on my gaming box - Windows 8.1, Radeon HD 7850, Catalyst 14.12

It turns out that this is a regression introduced in the ANGLE engine in Firefox 38. It worked fine in Firefox 37. Looks like it's still broken in beta (39) and aurora (40).

It's really strange that this works in Chrome - they are both using the ANGLE engine. However, Chrome often ships a newer version than Firefox has.
It could be that the issue is already fixed in the version of ANGLE in Chrome.
I'll look into filing a bug in the Firefox bug tracker.

**Closed as completed** 2015-06-03 01:38 UTC
Labels: browser-bug, firefox
